//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblYeuCau
    {
        public string MaSach { get; set; }
        public string MaDocgia { get; set; }
        public System.DateTime Ngaymuon { get; set; }
        public System.DateTime Ngaytra { get; set; }
    
        public virtual tblDocGia tblDocGia { get; set; }
        public virtual tblSach tblSach { get; set; }
    }
}
